// src/features/convenios/mock/conveniosMock.ts
export type ConvenioItem = {
  id: number;
  nombre: string;
  institucion: string;
  tipo: "beca" | "servicio_social" | "bolsa_trabajo";
  fechaInicio: string; // YYYY-MM-DD
  fechaFin: string;    // YYYY-MM-DD
  beneficio?: string | null;
  contactoNombre?: string | null;
  contactoEmail?: string | null;
  contactoTelefono?: string | null;
  archivoUrl?: string | null; // PDF
  activo: boolean;
};

export const conveniosMock: ConvenioItem[] = [
  {
    id: 1,
    nombre: "Convenio de Beca 20%",
    institucion: "Universidad Alfa",
    tipo: "beca",
    fechaInicio: "2025-01-01",
    fechaFin: "2025-12-31",
    beneficio: "Beca del 20% en colegiatura",
    contactoNombre: "Laura Gómez",
    contactoEmail: "laura.gomez@ualfa.edu",
    contactoTelefono: "555-100-2000",
    archivoUrl: null,
    activo: true,
  },
  {
    id: 2,
    nombre: "Servicio Social Ingeniería",
    institucion: "TecnoCorp",
    tipo: "servicio_social",
    fechaInicio: "2025-03-01",
    fechaFin: "2025-09-30",
    beneficio: "Cupos garantizados para 30 alumnos",
    contactoNombre: "Ing. Carlos Ruiz",
    contactoEmail: "cruiz@tecnocorp.com",
    contactoTelefono: "555-200-3000",
    archivoUrl: "https://ejemplo.com/convenio-2.pdf",
    activo: true,
  },
  {
    id: 3,
    nombre: "Bolsa de Trabajo TI",
    institucion: "SoftJobs",
    tipo: "bolsa_trabajo",
    fechaInicio: "2025-02-15",
    fechaFin: "2026-02-14",
    beneficio: "Acceso a vacantes junior TI",
    contactoNombre: "RH SoftJobs",
    contactoEmail: "talento@softjobs.io",
    contactoTelefono: "555-300-4000",
    archivoUrl: null,
    activo: true,
  },
  {
    id: 4,
    nombre: "Beca Excelencia 30%",
    institucion: "Colegio Beta",
    tipo: "beca",
    fechaInicio: "2024-08-01",
    fechaFin: "2025-07-31",
    beneficio: "30% para promedios ≥ 9.0",
    contactoNombre: "Mtra. Elisa Pérez",
    contactoEmail: "eperez@colegiobeta.edu",
    contactoTelefono: "555-400-5000",
    archivoUrl: null,
    activo: true,
  },
  {
    id: 5,
    nombre: "Convenio Clínica Dental",
    institucion: "SmileCare",
    tipo: "servicio_social",
    fechaInicio: "2024-10-01",
    fechaFin: "2025-10-01",
    beneficio: "Prácticas para Odontología",
    contactoNombre: "Dra. Diana Lara",
    contactoEmail: "dlara@smilecare.mx",
    contactoTelefono: "555-500-6000",
    archivoUrl: "https://ejemplo.com/convenio-5.pdf",
    activo: true,
  },
  {
    id: 6,
    nombre: "Beca Deportivo 15%",
    institucion: "Club Atletas",
    tipo: "beca",
    fechaInicio: "2025-05-01",
    fechaFin: "2025-11-30",
    beneficio: "15% para selección representativa",
    contactoNombre: "Coach Miguel",
    contactoEmail: "coach@clubatletas.mx",
    contactoTelefono: "555-600-7000",
    archivoUrl: null,
    activo: true,
  },
  {
    id: 7,
    nombre: "Prácticas Hospitalarias",
    institucion: "Hospital Central",
    tipo: "servicio_social",
    fechaInicio: "2024-09-01",
    fechaFin: "2025-03-01",
    beneficio: "Turnos clínicos supervisados",
    contactoNombre: "Lic. Araceli Núñez",
    contactoEmail: "anunez@hcentral.mx",
    contactoTelefono: "555-700-8000",
    archivoUrl: null,
    activo: false,
  },
  {
    id: 8,
    nombre: "Bolsa Trabajo Marketing",
    institucion: "MarketPlus",
    tipo: "bolsa_trabajo",
    fechaInicio: "2025-04-10",
    fechaFin: "2026-04-09",
    beneficio: "Vacantes Trainee Marketing",
    contactoNombre: "RRHH MarketPlus",
    contactoEmail: "rrhh@marketplus.com",
    contactoTelefono: "555-800-9000",
    archivoUrl: null,
    activo: true,
  },
  {
    id: 9,
    nombre: "Beca 10% Convenio Municipal",
    institucion: "Ayuntamiento León",
    tipo: "beca",
    fechaInicio: "2024-01-01",
    fechaFin: "2024-12-31",
    beneficio: "10% para servidores públicos",
    contactoNombre: "Lic. Ramón Silva",
    contactoEmail: "rsilva@zeta.gob.mx",
    contactoTelefono: "555-900-0000",
    archivoUrl: null,
    activo: false,
  },
  {
    id: 10,
    nombre: "Residencias Desarrollo Web",
    institucion: "WebLabs",
    tipo: "servicio_social",
    fechaInicio: "2025-06-01",
    fechaFin: "2025-12-01",
    beneficio: "Residencias con mentoría",
    contactoNombre: "Ana Torres",
    contactoEmail: "ana@weblabs.dev",
    contactoTelefono: "555-010-0200",
    archivoUrl: "https://ejemplo.com/convenio-10.pdf",
    activo: true,
  },
];
